### ISSUE TITLE
Got unexpected server response (405) while try to use the code.

### ISSUE THREAD

**Issue by diaolanshan** [SolaceSamples/solace-samples-nodejs#28]
Dear team, 

   I try to use the QueueProducer.js to publish a message using REST to our solace pubsub, but I always got success error .

*** Producer to queue "tutorial/queue" is ready to connect ***
[11:49:28] Connecting to Solace message router using url: http://10.49.0.172:9000
[11:49:28] Client username: test_user
[11:49:28] Solace message router VPN name: default
[11:50:28] Connection failed to the message router: Connection error: unexpected server response (405) - check correct parameter values and connectivity!
[11:50:28] { sessionEventCode: 'CONNECT_FAILED_ERROR (2)',
  infoStr: 'Connection error: unexpected server response (405)',
  responseCode: undefined,
  errorSubcode: 'CONNECTION_ERROR (44)',
  correlationKey: null }

do you have any idea why it didn't work for me?

I am pretty sure, the username and password I used is correct.

**Comment by mdspielman** [comment]
I believe you're using the wrong port. You cannot use QueueProducer.js to publish a REST message. These samples show how to use the Solace NodeJs API. So for that to work, you have to use the Web Transport ports which is often port 80 or 443 on the PubSub+ Broker. Here is a link to more details on ports: https://docs.solace.com/Configuring-and-Managing/SW-Broker-Specific-Config/SW-Broker-Configuration-Defaults.htm.

Can you try this and let me know if that helps.

For samples on publishing using a REST API for messages see: https://github.com/SolaceSamples/solace-samples-rest-messaging

**Comment by mdspielman** [comment]
You are correct. For the MQTT, JMS, REST, and AMQP, we have individual sample repositories in this organization. Here is a link to how you can browse them easily:

* https://cloud.solace.com/learn/group_quick_starts/gqs_using_messaging_apis.html
* https://cloud.solace.com/learn/group_quick_starts/gqs_using_open_apis.html

**Comment by mdspielman** [comment]
Here is an updated set of links because the above are no longer valid:
* https://docs.solace.com/Solace-PubSub-Messaging-APIs/Solace-APIs-Overview.htm
* https://docs.solace.com/Open-APIs-Protocols/Open-APIs-Protocols.htm
