### ISSUE TITLE
Transactional messaging support

### ISSUE THREAD

**Issue by lakshmi-github** [SolaceSamples/solace-samples-nodejs#35]
Hello,

Our team is considering implementing a nodejs app that will read certain meta data messages from a Solace queue, then perform post-processing on it. We wanted to use transactional messaging where a read would be committed only after successful post-processing of the message.

I was wondering if there are any plans to support transactional messaging in the Solace Nodejs API, as it currently is not supported?

Thanks.

**Comment by Mrc0113** [comment]
Closing stale issue due to inactivity. 😴
To have this issue re-opened please add a comment below with a detailed explanation.
Thank you for your contributions ❤️
