### ISSUE TITLE
If solace queue is restarted, the consumer not reconnect

### ISSUE THREAD

**Issue by Sicmatr1x** [SolaceSamples/solace-samples-nodejs#37]
After the consumer is connected to a solace queue, and the solace queue server is restarted, the consumer will disconnected to this queue forever.

This is the consumer would output.

```
=== An error happened, the message consumer is down ===
```

And you can see there will have no consumer though the queue monitor.

This was happend in **PRODUCT ENVIRONMENT**, and when I restart the progress which is consumming the msg, it reconnected again.

**Comment by gingerwilliams** [comment]
is this API still actively supported?

**Comment by Mrc0113** [comment]
Hi @gingerwilliams, yes the Solace NodeJS API fully supported. 

Closing this issue as it's old, but in general these are sample apps to get you started and items like error handling and retries should be thoroughly investigated before deploying any app to production.  

Please head over to the https://solace.community for general guidance. 

For retries there are several tuneable parameters available on the Solace Session, a few are depicted here: 
![image](https://user-images.githubusercontent.com/1815312/116609618-92a13800-a902-11eb-87b9-2a21c671089a.png)

More can be found in the [docs](https://docs.solace.com/API-Developer-Online-Ref-Documentation/nodejs/index.html)
