### ISSUE TITLE
Sending Chinese will result in garbled characters

### ISSUE THREAD

**Issue by josenspire** [SolaceSamples/solace-samples-nodejs#38]
Sending Chinese will result in garbled characters, only happen on js?

**Comment by aaron-613** [comment]
Sometimes with extended character sets, there is some additional encoding/decoding between JavaScript's UTF-16 default format, and Solace's supported UTF-8 format.  If using "standard" ASCII characters, everything will work fine, but once you move into the extended character sets, you need to ensure you do this conversion.

See a blog I found a while ago for more info: http://ecmanaut.blogspot.hk/2006/07/encoding-decoding-utf8-in-javascript.html

```
    function decode_utf8(s) {
        return decodeURIComponent(escape(s));
    }

    function encode_utf8(s) {
        return unescape(encodeURIComponent(s));
    }
```

Then, when you receive a message, try to decode the payload string using this function:

```
            if (msgType == 'BINARY') {
                try {
                    payload = JSON.parse(decode_utf8(message.getBinaryAttachment()));
```

Then when you send, it's something similar:

```
        var jsonPayload = JSON.stringify(payload);  // still UTF-16
        message.setBinaryAttachment(encode_utf8(jsonPayload));  // change to UTF-8
```

Does that help?

**Comment by Mrc0113** [comment]
@josenspire since @aaron-613 didn't tag you I just wanted to make sure you saw his response above. Did that solve the issue for you?
